package GUI;

import Classes.Dono;
import Classes.Ficheiro;
import Classes.TipoRecinto;
import Classes.Recinto;
import javax.swing.JOptionPane;

public class AdicionarRecinto extends javax.swing.JPanel {

   private Dono dono;
   private LoginDono parentFrame;
   private Recinto recinto;
   private boolean novoRecinto;

   public AdicionarRecinto(Dono dono, LoginDono parentFrame) {
      initComponents();
      this.novoRecinto = true;
      this.jLabelRecinto.setVisible(false);
      this.dono = dono;
      this.parentFrame = parentFrame;
      this.recinto = new Recinto();

      for (TipoRecinto t : TipoRecinto.values()) {
         switch (t) {
            case campoArLivre:
               this.jTipoRecinto.addItem("campoArLivre");
               break;
            case ginasio:
               this.jTipoRecinto.addItem("ginasio");
               break;
            case recintoCoberto:
               this.jTipoRecinto.addItem("recintoCoberto");
               break;
            default:
               break;
         }
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jNomeRecinto = new javax.swing.JTextField();
      jLabelRecinto = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLocalidade = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jMorada = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jTipoRecinto = new javax.swing.JComboBox<>();
      BtnCancelar = new javax.swing.JButton();
      BtnAdicionar = new javax.swing.JButton();
      jLabel6 = new javax.swing.JLabel();

      setLayout(null);

      jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setText("Adicionar Recinto");
      add(jLabel1);
      jLabel1.setBounds(300, 220, 250, 33);

      jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(0, 0, 0));
      jLabel3.setText("Nome do Recinto:");
      add(jLabel3);
      jLabel3.setBounds(150, 290, 160, 30);

      jNomeRecinto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
      jNomeRecinto.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            jNomeRecintoFocusLost(evt);
         }
      });
      add(jNomeRecinto);
      jNomeRecinto.setBounds(310, 290, 225, 30);

      jLabelRecinto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jLabelRecinto.setForeground(new java.awt.Color(255, 51, 51));
      jLabelRecinto.setText("Recinto já existe.");
      add(jLabelRecinto);
      jLabelRecinto.setBounds(540, 295, 140, 19);

      jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(0, 0, 0));
      jLabel4.setText("Localidade:");
      add(jLabel4);
      jLabel4.setBounds(200, 330, 102, 30);

      jLocalidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
      add(jLocalidade);
      jLocalidade.setBounds(310, 330, 225, 30);

      jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(0, 0, 0));
      jLabel5.setText("Morada:");
      add(jLabel5);
      jLabel5.setBounds(230, 370, 71, 30);

      jMorada.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
      add(jMorada);
      jMorada.setBounds(310, 370, 225, 30);

      jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setText("Tipo de Recinto:");
      add(jLabel2);
      jLabel2.setBounds(160, 415, 150, 22);

      jTipoRecinto.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
      jTipoRecinto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo de Recinto" }));
      add(jTipoRecinto);
      jTipoRecinto.setBounds(310, 410, 225, 30);

      BtnCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
      BtnCancelar.setText("Cancelar");
      BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnCancelarActionPerformed(evt);
         }
      });
      add(BtnCancelar);
      BtnCancelar.setBounds(280, 470, 125, 35);

      BtnAdicionar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
      BtnAdicionar.setText("Adicionar");
      BtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnAdicionarActionPerformed(evt);
         }
      });
      add(BtnAdicionar);
      BtnAdicionar.setBounds(440, 470, 125, 35);

      jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
      jLabel6.setToolTipText("");
      add(jLabel6);
      jLabel6.setBounds(0, 0, 800, 600);
   }// </editor-fold>//GEN-END:initComponents

   private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
      if (novoRecinto) {
         this.parentFrame.trocaPainel(new MenuDono(this.dono, this.parentFrame));
      } else {
         this.parentFrame.trocaPainel(new ConsultarRecinto(this.parentFrame, this.dono));
      }
   }//GEN-LAST:event_BtnCancelarActionPerformed

   private void jNomeRecintoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNomeRecintoFocusLost
      boolean existe = false;
      for (Dono d : Ficheiro.getRepo().getDonos().values()) {
         for (Recinto r : d.getRecintos()) {
            if (this.jNomeRecinto.getText().equals(r.getNome())) {
               existe = true;
               break;
            }
         }
      }
      if (existe) {
         this.jLabelRecinto.setVisible(true);
         this.BtnAdicionar.setEnabled(false);
      } else {
         this.jLabelRecinto.setVisible(false);
         this.BtnAdicionar.setEnabled(true);
      }
   }//GEN-LAST:event_jNomeRecintoFocusLost

   private void BtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarActionPerformed
      if (this.jTipoRecinto.getSelectedIndex() == 0) {
         JOptionPane.showMessageDialog(null, "Tipo de Recinto inválido.\nSelecione uma das opções.", "Erro", JOptionPane.ERROR_MESSAGE);
      } else {
         String tipo = String.valueOf(this.jTipoRecinto.getSelectedItem());
         this.recinto.setNome(this.jNomeRecinto.getText());
         this.recinto.setLocalidade(this.jLocalidade.getText());
         this.recinto.setMorada(this.jMorada.getText());
         this.recinto.setTipoRecinto(TipoRecinto.valueOf(tipo));
         if (novoRecinto) {
            this.dono.getRecintos().add(this.recinto);
            Ficheiro.getRepo().getRecintoLocalidade().put(this.jLocalidade.getText(), this.recinto);
            JOptionPane.showMessageDialog(null, "Recinto registado com sucesso.");
            this.parentFrame.trocaPainel(new ConsultarDesporto(this.recinto, this.dono, this.parentFrame));
         } else {
            Ficheiro.getRepo().getRecintoLocalidade().remove(this.recinto.getLocalidade(), this.recinto);
            Ficheiro.getRepo().getRecintoLocalidade().put(this.recinto.getLocalidade(), this.recinto);
            JOptionPane.showMessageDialog(null, "Alterações efetuadas com sucesso.");
            this.parentFrame.trocaPainel(new ConsultarRecinto(this.parentFrame, this.dono));
         }
         Ficheiro.serializar("Ficheiro");
      }
   }//GEN-LAST:event_BtnAdicionarActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAdicionar;
   private javax.swing.JButton BtnCancelar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabelRecinto;
   private javax.swing.JTextField jLocalidade;
   private javax.swing.JTextField jMorada;
   private javax.swing.JTextField jNomeRecinto;
   private javax.swing.JComboBox<String> jTipoRecinto;
   // End of variables declaration//GEN-END:variables
}
