package GUI;

import Classes.Dono;
import Classes.Ficheiro;
import Classes.TipoRecinto;
import Classes.Recinto;
import javax.swing.JOptionPane;

public class AdicionarRecinto extends javax.swing.JPanel {

   private Dono dono;
   private LoginDono parentFrame;
   private Recinto recinto;

   public AdicionarRecinto(Dono dono, LoginDono parentFrame) {
      initComponents();
      this.jLabelRecinto.setVisible(false);
      this.dono = dono;
      this.parentFrame = parentFrame;
      this.recinto = new Recinto();

      for (TipoRecinto t : TipoRecinto.values()) {
         switch (t) {
            case campoArLivre:
               this.jTipoRecinto.addItem("Campo ao ar livre");
               break;
            case ginasio:
               this.jTipoRecinto.addItem("Ginásio");
               break;
            case recintoCoberto:
               this.jTipoRecinto.addItem("Recinto Coberto");
               break;
            default:
               break;
         }
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNomeRecinto = new javax.swing.JTextField();
        jLabelRecinto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLocalidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMorada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTipoRecinto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Adicionar Recinto");
        add(jLabel1);
        jLabel1.setBounds(280, 250, 250, 33);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome do Recinto:");
        add(jLabel3);
        jLabel3.setBounds(145, 330, 160, 30);

        jNomeRecinto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jNomeRecinto);
        jNomeRecinto.setBounds(310, 330, 225, 30);

        jLabelRecinto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelRecinto.setForeground(new java.awt.Color(255, 51, 51));
        jLabelRecinto.setText("Recinto já existe!");
        add(jLabelRecinto);
        jLabelRecinto.setBounds(545, 335, 140, 19);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Localidade:");
        add(jLabel4);
        jLabel4.setBounds(200, 370, 102, 30);

        jLocalidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jLocalidade);
        jLocalidade.setBounds(310, 370, 225, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Morada:");
        add(jLabel5);
        jLabel5.setBounds(230, 410, 71, 30);

        jMorada.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jMorada);
        jMorada.setBounds(310, 410, 225, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de Recinto:");
        add(jLabel2);
        jLabel2.setBounds(160, 455, 150, 22);

        jTipoRecinto.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jTipoRecinto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo de Recinto" }));
        jTipoRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoRecintoActionPerformed(evt);
            }
        });
        add(jTipoRecinto);
        jTipoRecinto.setBounds(310, 450, 225, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
        jLabel6.setToolTipText("");
        add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jTipoRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoRecintoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipoRecintoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelRecinto;
    private javax.swing.JTextField jLocalidade;
    private javax.swing.JTextField jMorada;
    private javax.swing.JTextField jNomeRecinto;
    private javax.swing.JComboBox<String> jTipoRecinto;
    // End of variables declaration//GEN-END:variables
}
