package GUI;

import Classes.Ficheiro;
import Classes.Dono;
import Classes.Recinto;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ConsultarRecinto extends javax.swing.JPanel {

   private LoginDono parentFrameDono;
   private LoginAdmin parentFrameAdmin;
   private Dono dono;
   private String admin;

   public ConsultarRecinto(LoginAdmin parentFrame, String admin) {
      initComponents();
      this.admin = admin;
      this.parentFrameAdmin = parentFrame;
      this.BtnEditarRecinto.setEnabled(false);
      this.BtnReservas.setEnabled(false);
      this.BtnHorarios.setEnabled(false);
      this.BtnDesportos.setVisible(false);
      this.BtnServicos.setVisible(false);
      DefaultTableModel table = (DefaultTableModel) this.jTable.getModel();

      for (Map.Entry<String, Dono> mapa : Ficheiro.getRepo().getDonos().entrySet()) {
         for (Recinto r : mapa.getValue().getRecintos()) {
            table.addRow(new Object[]{mapa.getValue().getNickname(), r.getNome(), r.getEmpresa(), r.getMorada(), r.getLocalidade(), r.isAtivo()});
         }
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnEditarRecinto = new javax.swing.JButton();
        BtnReservas = new javax.swing.JButton();
        BtnHorarios = new javax.swing.JButton();
        BtnDesportos = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        BtnServicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Recintos");
        add(jLabel1);
        jLabel1.setBounds(270, 210, 130, 35);

        BtnEditarRecinto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnEditarRecinto.setText("Editar Recinto");
        add(BtnEditarRecinto);
        BtnEditarRecinto.setBounds(40, 260, 175, 40);

        BtnReservas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnReservas.setText("Consultar Reservas");
        add(BtnReservas);
        BtnReservas.setBounds(40, 310, 175, 40);

        BtnHorarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnHorarios.setText("Consultar Horários");
        add(BtnHorarios);
        BtnHorarios.setBounds(40, 360, 175, 40);

        BtnDesportos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnDesportos.setText("Consultar Desportos");
        add(BtnDesportos);
        BtnDesportos.setBounds(40, 410, 175, 40);

        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        add(BtnVoltar);
        BtnVoltar.setBounds(600, 520, 175, 40);

        BtnServicos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnServicos.setText("Consultar Serviços");
        add(BtnServicos);
        BtnServicos.setBounds(40, 460, 175, 40);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dono", "Recinto", "Desporto", "Tipo de Recinto", "Localidade", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(270, 260, 500, 240);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
        jLabel3.setToolTipText("");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

   private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
      boolean ativado = true;
      if (this.parentFrameDono != null) {
         Recinto recinto = null;
         String nome = (String) this.jTable.getValueAt(this.jTable.getSelectedRow(), 0);
         for (Recinto r : this.dono.getRecintos()) {
            if (r.getNome().equals(nome)) {
               recinto = r;
            }
         }
         if (!recinto.isAtivo()) {
            ativado = false;
            this.jTable.clearSelection();
         }
      }
      if (ativado) {
         this.BtnEditarRecinto.setEnabled(true);
         this.BtnReservas.setEnabled(true);
         this.BtnHorarios.setEnabled(true);
         this.BtnDesportos.setVisible(true);
         this.BtnServicos.setVisible(true);
      }
   }//GEN-LAST:event_jTableMouseClicked

   private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
      if (this.parentFrameAdmin != null) {
            this.parentFrameAdmin.trocaPainel(new MenuAdmin(this.admin, this.parentFrameAdmin));
        } else {
            this.parentFrameDono.trocaPainel(new MenuDono(this.dono, this.parentFrameDono));
        }
   }//GEN-LAST:event_BtnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDesportos;
    private javax.swing.JButton BtnEditarRecinto;
    private javax.swing.JButton BtnHorarios;
    private javax.swing.JButton BtnReservas;
    private javax.swing.JButton BtnServicos;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
