package GUI;

import Classes.Ficheiro;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class LoginAdmin extends javax.swing.JFrame implements Runnable {

   private JPanel painelVisivel;
   private String admin;

   public LoginAdmin() {
      initComponents();
      setResizable(false);
      setSize(800, 630);
      Ficheiro.desserializar("Ficheiro");
      this.setLocationRelativeTo(null);
      this.painelVisivel = this.jPanelLogin;
      this.jMenuBar.setVisible(false);
      if (Ficheiro.getRepo().getAdmins().size() == 0) {
         Ficheiro.getRepo().getAdmins().put("", "");
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelLogin = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jUsername = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jPassword = new javax.swing.JPasswordField();
      BtnLogin = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      jMenuBar = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenuItem5 = new javax.swing.JMenuItem();
      jMenu2 = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      jSeparator2 = new javax.swing.JPopupMenu.Separator();
      jMenuItem2 = new javax.swing.JMenuItem();
      jSeparator3 = new javax.swing.JPopupMenu.Separator();
      jSeparator4 = new javax.swing.JPopupMenu.Separator();
      jMenuItem4 = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Sportshut - Gestão de Reservas em Campos Desportivos - Admin");

      jPanelLogin.setLayout(null);

      jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setText("Password:");
      jPanelLogin.add(jLabel2);
      jLabel2.setBounds(215, 350, 100, 24);

      jUsername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jPanelLogin.add(jUsername);
      jUsername.setBounds(330, 310, 200, 30);

      jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(0, 0, 0));
      jLabel3.setText("Username:");
      jPanelLogin.add(jLabel3);
      jLabel3.setBounds(215, 310, 110, 24);

      jPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            jPasswordKeyPressed(evt);
         }
      });
      jPanelLogin.add(jPassword);
      jPassword.setBounds(330, 350, 200, 30);

      BtnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
      BtnLogin.setText("Login");
      BtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      BtnLogin.setPreferredSize(new java.awt.Dimension(100, 35));
      BtnLogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnLoginActionPerformed(evt);
         }
      });
      jPanelLogin.add(BtnLogin);
      BtnLogin.setBounds(360, 400, 150, 35);

      jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
      jLabel4.setToolTipText("");
      jPanelLogin.add(jLabel4);
      jLabel4.setBounds(0, 0, 800, 600);

      jMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      jMenu1.setText("Menu Inicial");

      jMenuItem5.setText("Voltar");
      jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem5ActionPerformed(evt);
         }
      });
      jMenu1.add(jMenuItem5);

      jMenuBar.add(jMenu1);

      jMenu2.setText("Opções");

      jMenuItem1.setText("Criar Novo Admin");
      jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
         }
      });
      jMenu2.add(jMenuItem1);
      jMenu2.add(jSeparator2);

      jMenuItem2.setText("Listar Recintos");
      jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
         }
      });
      jMenu2.add(jMenuItem2);
      jMenu2.add(jSeparator3);
      jMenu2.add(jSeparator4);

      jMenuItem4.setText("Listar Utilizadores");
      jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
         }
      });
      jMenu2.add(jMenuItem4);

      jMenuBar.add(jMenu2);

      setJMenuBar(jMenuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   public void trocaPainel(JPanel painel) {
      this.painelVisivel.setVisible(false);
      this.painelVisivel = painel;
      this.setContentPane(this.painelVisivel);
      this.painelVisivel.setVisible(true);
   }

   // Verificar se o utilizador clica no "Enter" para efetuar login.
   private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         this.BtnLogin.doClick();
      }
   }//GEN-LAST:event_jPasswordKeyPressed

   private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
      String a = null;
      if (Ficheiro.getRepo().getAdmins().containsKey(this.jUsername.getText())) {
         a = Ficheiro.getRepo().getAdmins().get(this.jUsername.getText());
         if (a.equals(new String(this.jPassword.getPassword()))) {
            this.admin = a;
            JOptionPane.showMessageDialog(rootPane, "Autenticado com sucesso!");
            this.trocaPainel(new MenuAdmin(a, this));
            System.out.println("Login como Admin efetuado com sucesso.");
            this.jMenuBar.setVisible(true);
         } else {
            JOptionPane.showMessageDialog(rootPane, "Senha Incorreta!", "Erro", JOptionPane.ERROR_MESSAGE);
         }
      } else {
         JOptionPane.showMessageDialog(rootPane, "Administrador não existente!", "Erro", JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_BtnLoginActionPerformed

   private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      //this.trocaPainel(new RegistarAdmin(this, this.admin));
   }//GEN-LAST:event_jMenuItem1ActionPerformed

   private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jMenuItem2ActionPerformed

   private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jMenuItem4ActionPerformed

   private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
      this.trocaPainel(new MenuAdmin(this.admin, this));
   }//GEN-LAST:event_jMenuItem5ActionPerformed

   @Override
   public void run() {
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new LoginAdmin().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnLogin;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem4;
   private javax.swing.JMenuItem jMenuItem5;
   private javax.swing.JPanel jPanelLogin;
   private javax.swing.JPasswordField jPassword;
   private javax.swing.JPopupMenu.Separator jSeparator2;
   private javax.swing.JPopupMenu.Separator jSeparator3;
   private javax.swing.JPopupMenu.Separator jSeparator4;
   private javax.swing.JTextField jUsername;
   // End of variables declaration//GEN-END:variables
}
