package GUI;

import Classes.Cliente;
import Classes.Ficheiro;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class LoginCliente extends javax.swing.JFrame implements Runnable {

   private JPanel painelVisivel;
   private Cliente cliente;
   
   public LoginCliente() {
      initComponents();
      setResizable(false);
      setSize(800, 630);
      Ficheiro.desserializar("Ficheiro");
      this.setLocationRelativeTo(null);
      this.painelVisivel = this.jPanelLogin;
      this.jMenuBar.setVisible(false);
      this.cliente = new Cliente();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelLogin = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jUsername = new javax.swing.JTextField();
      jPassword = new javax.swing.JPasswordField();
      BtnLogin = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      jMenuBar = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenuItemVoltar = new javax.swing.JMenuItem();
      jMenu2 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Sportshut - Gestão de Reservas em Campos Desportivos - Cliente");

      jPanelLogin.setLayout(null);

      jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setText("Username:");
      jPanelLogin.add(jLabel1);
      jLabel1.setBounds(245, 300, 110, 24);

      jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(0, 0, 0));
      jLabel2.setText("Password:");
      jPanelLogin.add(jLabel2);
      jLabel2.setBounds(245, 350, 100, 24);

      jUsername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jPanelLogin.add(jUsername);
      jUsername.setBounds(360, 300, 200, 30);

      jPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            jPasswordKeyPressed(evt);
         }
      });
      jPanelLogin.add(jPassword);
      jPassword.setBounds(360, 350, 200, 30);

      BtnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
      BtnLogin.setText("Login");
      BtnLogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnLoginActionPerformed(evt);
         }
      });
      jPanelLogin.add(BtnLogin);
      BtnLogin.setBounds(380, 400, 150, 35);

      jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
      jLabel4.setToolTipText("");
      jPanelLogin.add(jLabel4);
      jLabel4.setBounds(0, 0, 800, 600);

      jMenu1.setText("Menu Inicial");

      jMenuItemVoltar.setText("Voltar");
      jMenuItemVoltar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemVoltarActionPerformed(evt);
         }
      });
      jMenu1.add(jMenuItemVoltar);

      jMenuBar.add(jMenu1);

      jMenu2.setText("Opções");
      jMenuBar.add(jMenu2);

      setJMenuBar(jMenuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
      Cliente c = new Cliente();
      if (Ficheiro.getRepo().getClientes().containsKey(this.jUsername.getText())) {
         c = Ficheiro.getRepo().getClientes().get(this.jUsername.getText());
         if (c.getSenha().equals(new String(this.jPassword.getPassword()))) {
            this.cliente = c;
            JOptionPane.showMessageDialog(null, "Autenticado com sucesso!");
            this.trocaPainel(new MenuCliente(this.cliente, this));
            System.out.println("Login como Cliente efetuado com sucesso.");
            this.jMenuBar.setVisible(true);
         } else {
            JOptionPane.showMessageDialog(null, "Senha Incorreta!", "Erro", JOptionPane.ERROR_MESSAGE);
         }
      } else {
         JOptionPane.showMessageDialog(null, "Usuário não existente!\nRegiste-se e tente outra vez.", "Erro", JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_BtnLoginActionPerformed

   private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         this.BtnLogin.doClick();
      }
   }//GEN-LAST:event_jPasswordKeyPressed

   private void jMenuItemVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVoltarActionPerformed
      this.cliente = (Cliente) Ficheiro.getRepo().getClientes().get(this.cliente.getNickname());
      this.trocaPainel(new MenuCliente(this.cliente, this));
   }//GEN-LAST:event_jMenuItemVoltarActionPerformed

   public void trocaPainel(JPanel painel) {
      this.painelVisivel.setVisible(false);
      this.painelVisivel = painel;
      this.setContentPane(this.painelVisivel);
      this.painelVisivel.setVisible(true);
   }
   
   @Override
   public void run() {
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new LoginCliente().setVisible(true);
         }
      });
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnLogin;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar;
   private javax.swing.JMenuItem jMenuItemVoltar;
   private javax.swing.JPanel jPanelLogin;
   private javax.swing.JPasswordField jPassword;
   private javax.swing.JTextField jUsername;
   // End of variables declaration//GEN-END:variables
}
