package GUI;

import Classes.Cliente;

public class MenuCliente extends javax.swing.JPanel {

   private Cliente cliente;
   private LoginCliente parentFrame;

   public MenuCliente(Cliente cliente, LoginCliente parentFrame) {
      initComponents();
      this.cliente = cliente;
      this.parentFrame = parentFrame;
      this.cliente.setNumPontos(100);
      this.jCliente.setText("Bem Vindo " + this.cliente.getNickname());
      this.jPontosCliente.setText("Pontos do Cliente: " + Integer.toString(this.cliente.getNumPontos()));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jCliente = new javax.swing.JLabel();
      BtnListRecintos = new javax.swing.JButton();
      BtnPesquisarRecinto = new javax.swing.JButton();
      jPontosCliente = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();

      setLayout(null);

      jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setText("O que deseja fazer?");
      add(jLabel1);
      jLabel1.setBounds(300, 430, 203, 26);

      jCliente.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
      jCliente.setForeground(new java.awt.Color(0, 0, 0));
      jCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jCliente.setText("Bem Vindo cliente.");
      add(jCliente);
      jCliente.setBounds(0, 310, 800, 50);

      BtnListRecintos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
      BtnListRecintos.setText("Consultar Reservas");
      BtnListRecintos.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnListRecintosActionPerformed(evt);
         }
      });
      add(BtnListRecintos);
      BtnListRecintos.setBounds(400, 470, 200, 35);

      BtnPesquisarRecinto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
      BtnPesquisarRecinto.setText("Pesquisar Recinto");
      BtnPesquisarRecinto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnPesquisarRecintoActionPerformed(evt);
         }
      });
      add(BtnPesquisarRecinto);
      BtnPesquisarRecinto.setBounds(190, 470, 200, 35);

      jPontosCliente.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
      jPontosCliente.setForeground(new java.awt.Color(0, 0, 0));
      jPontosCliente.setText("Pontos do cliente: xxxx");
      add(jPontosCliente);
      jPontosCliente.setBounds(10, 550, 490, 34);

      jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
      jLabel4.setToolTipText("");
      add(jLabel4);
      jLabel4.setBounds(0, 0, 800, 600);
   }// </editor-fold>//GEN-END:initComponents

   private void BtnPesquisarRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarRecintoActionPerformed

   }//GEN-LAST:event_BtnPesquisarRecintoActionPerformed

   private void BtnListRecintosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListRecintosActionPerformed

   }//GEN-LAST:event_BtnListRecintosActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnListRecintos;
   private javax.swing.JButton BtnPesquisarRecinto;
   private javax.swing.JLabel jCliente;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jPontosCliente;
   // End of variables declaration//GEN-END:variables
}
