package GUI;

import Classes.Ficheiro;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MenuInicial extends javax.swing.JFrame {

   private JPanel painelVisivel;

   public MenuInicial() {
      initComponents();
      setResizable(false);
      setSize(800, 630);
      this.setLocationRelativeTo(null);
      this.painelVisivel = this.jPanelInicial;
      Ficheiro.desserializar("Ficheiro");
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnAdmin = new javax.swing.JButton();
        BtnRegistar = new javax.swing.JButton();
        BtnDonoRecinto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sportshut - Gestão de Reservas em Campos Desportivos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelInicial.setBackground(new java.awt.Color(204, 204, 204));
        jPanelInicial.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanelInicial.add(jLabel3);
        jLabel3.setBounds(280, 120, 250, 61);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestão de Reservas");
        jPanelInicial.add(jLabel1);
        jLabel1.setBounds(250, 60, 310, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Não possui conta?");
        jPanelInicial.add(jLabel4);
        jLabel4.setBounds(520, 340, 180, 26);

        BtnAdmin.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        BtnAdmin.setText("Admin");
        BtnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminActionPerformed(evt);
            }
        });
        jPanelInicial.add(BtnAdmin);
        BtnAdmin.setBounds(130, 320, 200, 40);

        BtnRegistar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        BtnRegistar.setText("Registar");
        BtnRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistarActionPerformed(evt);
            }
        });
        jPanelInicial.add(BtnRegistar);
        BtnRegistar.setBounds(510, 380, 200, 40);

        BtnDonoRecinto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        BtnDonoRecinto.setText("Dono de Recinto");
        BtnDonoRecinto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDonoRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDonoRecintoActionPerformed(evt);
            }
        });
        jPanelInicial.add(BtnDonoRecinto);
        BtnDonoRecinto.setBounds(130, 380, 200, 40);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Entrar como:");
        jPanelInicial.add(jLabel5);
        jLabel5.setBounds(170, 280, 130, 26);

        BtnCliente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        BtnCliente.setText("Cliente");
        BtnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteActionPerformed(evt);
            }
        });
        jPanelInicial.add(BtnCliente);
        BtnCliente.setBounds(130, 440, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanelInicial.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void trocaPainel(JPanel painel) {
      this.painelVisivel.setVisible(false);
      this.painelVisivel = painel;
      this.setContentPane(this.painelVisivel);
      this.painelVisivel.setVisible(true);
   }

   public JPanel getPanelInicial() {
      return this.jPanelInicial;
   }
   
   private void BtnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistarActionPerformed
      this.trocaPainel(new RegistarUser(this));
   }//GEN-LAST:event_BtnRegistarActionPerformed

   private void BtnDonoRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDonoRecintoActionPerformed
      if (Ficheiro.getRepo().getDonos().size() == 0) {
         JOptionPane.showMessageDialog(rootPane, "Não existe nenhuma conta criada como dono.\nCrie primeiro uma conta.", "Erro", JOptionPane.ERROR_MESSAGE);
      } else {
         Thread t = new Thread(new LoginDono());
         t.start();
      }
   }//GEN-LAST:event_BtnDonoRecintoActionPerformed

   private void BtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteActionPerformed
      if (Ficheiro.getRepo().getClientes().size() == 0) {
         JOptionPane.showMessageDialog(rootPane, "Não existe nenhuma conta criada como cliente.\nCrie primeiro uma conta.", "Erro", JOptionPane.ERROR_MESSAGE);
      } else {
         Thread t = new Thread(new LoginCliente());
         t.start();
      }
   }//GEN-LAST:event_BtnClienteActionPerformed

   private void BtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminActionPerformed
      Thread t = new Thread(new LoginAdmin());
      t.start();
   }//GEN-LAST:event_BtnAdminActionPerformed

   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new MenuInicial().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdmin;
    private javax.swing.JButton BtnCliente;
    private javax.swing.JButton BtnDonoRecinto;
    private javax.swing.JButton BtnRegistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelInicial;
    // End of variables declaration//GEN-END:variables
}
