package GUI;

import Classes.Ficheiro;
import Classes.Cliente;
import Classes.Dono;
import Classes.Ficheiro;
import Classes.Utilizador;
import javax.swing.JOptionPane;

public class RegistarUser extends javax.swing.JPanel {

   private Utilizador novoUser;
   private MenuInicial parentFrame;

   public RegistarUser(MenuInicial parentFrame) {
      initComponents();
      this.parentFrame = parentFrame;
      this.jLabelUsername.setVisible(false);
      this.jLabelPassword.setVisible(false);
      this.BtnConcluir.setEnabled(false);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNomeCompleto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPassword1 = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jNumCC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jNIF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jNumTele = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMorada = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLocalidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCliente = new javax.swing.JRadioButton();
        jDono = new javax.swing.JRadioButton();
        BtnCancelar = new javax.swing.JButton();
        BtnConcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registar Nova Conta");
        add(jLabel1);
        jLabel1.setBounds(260, 40, 290, 33);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome Completo:");
        add(jLabel3);
        jLabel3.setBounds(60, 118, 160, 22);

        jUsername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFocusLost(evt);
            }
        });
        add(jUsername);
        jUsername.setBounds(220, 145, 200, 27);

        jLabelUsername.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 51, 51));
        jLabelUsername.setText("Username já existe.");
        add(jLabelUsername);
        jLabelUsername.setBounds(430, 150, 170, 24);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel4);
        jLabel4.setBounds(105, 148, 100, 22);

        jNomeCompleto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(jNomeCompleto);
        jNomeCompleto.setBounds(220, 113, 400, 27);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password:");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel5);
        jLabel5.setBounds(110, 179, 100, 22);
        add(jPassword);
        jPassword.setBounds(220, 177, 200, 27);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Confirmar Password:");
        add(jLabel6);
        jLabel6.setBounds(20, 212, 190, 22);

        jPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassword1FocusLost(evt);
            }
        });
        add(jPassword1);
        jPassword1.setBounds(220, 209, 200, 27);

        jLabelPassword.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 51, 51));
        jLabelPassword.setText("Passwords não coincidem.");
        add(jLabelPassword);
        jLabelPassword.setBounds(430, 210, 230, 24);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nº Cartão Cidadão:");
        add(jLabel7);
        jLabel7.setBounds(40, 243, 170, 22);

        jNumCC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(jNumCC);
        jNumCC.setBounds(220, 240, 120, 27);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NIF:");
        add(jLabel8);
        jLabel8.setBounds(170, 275, 40, 22);

        jNIF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(jNIF);
        jNIF.setBounds(220, 272, 120, 27);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nº Telemóvel:");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel9);
        jLabel9.setBounds(80, 308, 130, 22);

        jNumTele.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(jNumTele);
        jNumTele.setBounds(220, 305, 120, 27);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Morada:");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel10);
        jLabel10.setBounds(133, 340, 80, 22);

        jMorada.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(jMorada);
        jMorada.setBounds(220, 338, 400, 27);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Localidade:");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel12);
        jLabel12.setBounds(100, 370, 110, 22);

        jLocalidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(jLocalidade);
        jLocalidade.setBounds(220, 370, 400, 27);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Deseja Registar-se como:");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel11);
        jLabel11.setBounds(30, 435, 240, 22);

        jCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCliente.setForeground(new java.awt.Color(0, 0, 0));
        jCliente.setText("Cliente");
        jCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteActionPerformed(evt);
            }
        });
        add(jCliente);
        jCliente.setBounds(280, 430, 110, 30);

        jDono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDono.setForeground(new java.awt.Color(0, 0, 0));
        jDono.setText("Dono de Recinto");
        jDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDonoActionPerformed(evt);
            }
        });
        add(jDono);
        jDono.setBounds(450, 430, 180, 30);

        BtnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        add(BtnCancelar);
        BtnCancelar.setBounds(200, 500, 150, 35);

        BtnConcluir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnConcluir.setText("Concluir");
        BtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConcluirActionPerformed(evt);
            }
        });
        add(BtnConcluir);
        BtnConcluir.setBounds(440, 500, 150, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/campo-desportivo.png"))); // NOI18N
        jLabel2.setToolTipText("");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

   private void jUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusLost
      if (this.jDono.isSelected()) {
         if (Ficheiro.getRepo().getDonos().containsKey(this.jUsername.getText())) {
            this.jLabelUsername.setVisible(true);
            this.BtnConcluir.setEnabled(false);
         } else {
            this.jLabelUsername.setVisible(false);
            this.BtnConcluir.setEnabled(true);
         }
      } else {
         if (Ficheiro.getRepo().getClientes().containsKey(this.jUsername.getText())) {
            this.jLabelUsername.setVisible(true);
            this.BtnConcluir.setEnabled(false);
         } else {
            this.jLabelUsername.setVisible(false);
            this.BtnConcluir.setEnabled(true);
         }
      }
   }//GEN-LAST:event_jUsernameFocusLost

   private void jPassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword1FocusLost
      if (!new String(this.jPassword.getPassword()).equals(new String(this.jPassword1.getPassword()))) {
         this.jLabelPassword.setVisible(true);
         this.BtnConcluir.setEnabled(false);
      } else {
         this.jLabelPassword.setVisible(false);
         this.BtnConcluir.setEnabled(true);
      }
   }//GEN-LAST:event_jPassword1FocusLost

   private void jClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteActionPerformed
      this.BtnConcluir.setEnabled(true);
      this.jCliente.setSelected(true);
      this.novoUser = new Cliente();
      if (this.jDono.isSelected()) {
         this.jDono.setSelected(false);
      }
   }//GEN-LAST:event_jClienteActionPerformed

   private void jDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDonoActionPerformed
      this.BtnConcluir.setEnabled(true);
      this.jDono.setSelected(true);
      this.novoUser = new Dono();
      if (this.jCliente.isSelected()) {
         this.jCliente.setSelected(false);
      }
   }//GEN-LAST:event_jDonoActionPerformed

   private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
      this.parentFrame.trocaPainel(this.parentFrame.getPanelInicial());
   }//GEN-LAST:event_BtnCancelarActionPerformed

   private void BtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConcluirActionPerformed
      this.novoUser.setNome(this.jNomeCompleto.getText());
      this.novoUser.setNickname(this.jUsername.getText());
      this.novoUser.setSenha(new String(this.jPassword.getPassword()));
      this.novoUser.setNumCC(Integer.parseInt(this.jNumCC.getText()));
      this.novoUser.setNif(Integer.parseInt(this.jNIF.getText()));
      this.novoUser.setNumTele(Integer.parseInt(this.jNumTele.getText()));
      this.novoUser.setMorada(this.jMorada.getText());
      this.novoUser.setLocalidade(this.jLocalidade.getText());
      if (this.jCliente.isSelected()) {
         Ficheiro.getRepo().getClientes().put(this.novoUser.getNickname(), (Cliente) novoUser);
      } else {
         Ficheiro.getRepo().getDonos().put(this.novoUser.getNickname(), (Dono) novoUser);
      }
      JOptionPane.showMessageDialog(null, "Registo efetuado com sucesso!");
      Ficheiro.serializar("Ficheiro");
      this.parentFrame.trocaPainel(this.parentFrame.getPanelInicial());
   }//GEN-LAST:event_BtnConcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConcluir;
    private javax.swing.JRadioButton jCliente;
    private javax.swing.JRadioButton jDono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JTextField jLocalidade;
    private javax.swing.JTextField jMorada;
    private javax.swing.JTextField jNIF;
    private javax.swing.JTextField jNomeCompleto;
    private javax.swing.JTextField jNumCC;
    private javax.swing.JTextField jNumTele;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
